languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Mind Journey"
copyright = "&copy; 2024-2025 YOMO. All Rights Reserved. "

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Section 1 starts"

[params.author]
  name = "YOMO"
  image = "img/author.jpg"
  headline = "Tech veteran & trend trader"
  bio = "This is an example author bio"
  links = [
    { x-twitter = "https://x.com/yomo2077" },
#    { facebook = "https://facebook.com/" },
#    { linkedin = "https://linkedin.com/" },
#    { youtube = "https://youtube.com/" },
  ]
